HeadNode: 
  CustomActions: 
    OnNodeConfigured: 
      Script: "s3://hpc-scripts-ide-team-b8e821a/install-pwb-config.sh"
  Iam: 
    S3Access: 
      - BucketName: hpc-scripts-ide-team-b8e821a
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::749683154838:policy/elbaccess-e6042c3
  InstanceType: t3.xlarge
  Networking: 
    SubnetId: subnet-0193abae7b57c6521
    AdditionalSecurityGroups: 
      - sg-0bbe070666497e469
  LocalStorage:
    RootVolume:
      Size: 120 
  SharedStorageType: Efs
  Ssh:
    KeyName: sam.cofer@posit.co-keypair-for-pulumi 
Image: 
  Os: ubuntu2004
  CustomAmi: ami-0f44837ba2e027629
Region: us-west-2
Scheduling: 
  Scheduler: slurm
  SlurmSettings:
    EnableMemoryBasedScheduling: true
    Database:
      Uri: slurm-db7491e7a.cfnlgz1ljotq.us-west-2.rds.amazonaws.com:3306
      UserName: slurm_db_admin
      PasswordSecretArn: arn:aws:secretsmanager:us-west-2:749683154838:secret:SlurmDBPassword-0e52b9b-vqT4Ou
      DatabaseName: slurm    
  SlurmQueues: 

    - Name: interactive
      ComputeResources:
        - Name: rstudio 
          InstanceType: t3.xlarge
          MaxCount: 3
          MinCount: 1
          Efa:
            Enabled: FALSE
      CustomActions:
        OnNodeConfigured:
          Script: "s3://hpc-scripts-ide-team-b8e821a/config-compute.sh"
      Iam:
        S3Access:
          - BucketName: hpc-scripts-ide-team-b8e821a
      Networking:
        PlacementGroup:
          Enabled: FALSE
        SubnetIds:
          - subnet-0193abae7b57c6521

    - Name: all 
      ComputeResources:
        - Name: rstudio 
          InstanceType: t3.xlarge
          MaxCount: 2
          MinCount: 0
          Efa:
            Enabled: FALSE
      CustomActions:
        OnNodeConfigured:
          Script: "s3://hpc-scripts-ide-team-b8e821a/config-compute.sh"
      Iam:
        S3Access:
          - BucketName: hpc-scripts-ide-team-b8e821a
      Networking:
        PlacementGroup:
          Enabled: FALSE
        SubnetIds:
          - subnet-0193abae7b57c6521

    - Name: gpu 
      ComputeResources:
        - Name: large
          InstanceType: p3.2xlarge
          MaxCount: 1
          MinCount: 0
          Efa:
            Enabled: FALSE
      CustomActions:
        OnNodeConfigured:
          Script: "s3://hpc-scripts-ide-team-b8e821a/config-compute.sh"
      Iam:
        S3Access:
          - BucketName: hpc-scripts-ide-team-b8e821a
      Networking:
        PlacementGroup:
          Enabled: FALSE
        SubnetIds: 
          - subnet-0193abae7b57c6521


LoginNodes:
  Pools:
    - Name: login
      Count: 2 
      InstanceType: t3.xlarge
      Networking:
        AdditionalSecurityGroups: 
          - sg-0325f8a1f76ed3a4f
        SubnetIds: 
          - subnet-0193abae7b57c6521
      Ssh:
        KeyName: sam.cofer@posit.co-keypair-for-pulumi 

DevSettings:
  Timeouts:
    HeadNodeBootstrapTimeout: 7200  # timeout in seconds
    ComputeNodeBootstrapTimeout: 7200  # timeout in seconds

SharedStorage:
  - MountDir: /home
    Name: home
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: SCRATCH_2
  - MountDir: /opt/rstudio
    Name: rstudio
    StorageType: Efs
    EfsSettings:
        Encrypted: True
        EncryptionInTransit: True
DirectoryService:
  DomainName: pwb.posit.co
  DomainAddr: ldap://pwb.posit.co
  PasswordSecretArn: arn:aws:secretsmanager:us-west-2:749683154838:secret:SimpleADPassword-3c16224-J8p3yl
  DomainReadOnlyUser: cn=Administrator,cn=Users,dc=pwb,dc=posit,dc=co
  GenerateSshKeysForUsers: true
  AdditionalSssdConfigs: 
    override_homedir : /home/%u
    ldap_id_use_start_tls : false
    ldap_tls_reqcert : never
    ldap_auth_disable_tls_never_use_in_production : true

Tags:
  - Key: rs:environment
    Value: development
  - Key: rs:owner
    Value: sam.cofer@posit.co 
  - Key: rs:project
    Value: solutions
  - Key: rs:subsystem
    Value: load-testing
