set shell := ["bash"]

create-users num="10":
    #!/bin/bash
    # set SSH_AUTH_SOCK env var to a fixed value
    export SSH_AUTH_SOCK=~/.ssh/ssh-agent.sock

    # test whether $SSH_AUTH_SOCK is valid
    ssh-add -l 2>/dev/null >/dev/null

    # if not valid, then start ssh-agent using $SSH_AUTH_SOCK
    [ $? -ge 2 ] && ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null

    ssh-add  - <<< "$(pulumi stack output --show-secrets 'private_key_ssh')"
    ssh \
        -o StrictHostKeyChecking=no \
        ubuntu@$(pulumi stack output jump_host_public_ip) \
        "bash useradd.sh {{num}}"


up: 
    #!/bin/bash
    pulumi up -y
    just create-users  
