key-pair-new:
    just key-pair-new-script
    chmod 400 key.pem
    cat key.pem.pub | pulumi config set public_key

key-pair-delete:
    rm -f key.pem key.pem.pub

key-pair-new-script:
   echo "" | ssh-keygen -t rsa -f key.pem

create-users num="10":
    ssh \
        -i key.pem \
        -o StrictHostKeyChecking=no \
        ubuntu@$(pulumi stack output ad_jump_host_public_ip) \
        "bash useradd.sh {{num}}"


up: 
    pulumi up -y
    just create-users 500 