set shell := ["bash"]

create-users num="10":
    #!/bin/bash
    ssh \
        -i "$(pulumi stack output 'key_pair id').pem" \
        -o StrictHostKeyChecking=no \
        ubuntu@$(pulumi stack output ad_jump_host_public_ip) \
        "bash useradd.sh {{num}}"

create-secrets:
    #!/bin/bash
    export email=`pulumi config get email`
    export keyname="${email}-keypair-for-pulumi"
    aws ec2 describe-key-pairs --key-names=$keyname
    if [ $? -ne 0 ]; then 
        echo "Key $keyname does not seem to exist, let's create a new one."
        aws ec2 create-key-pair --key-name $keyname --query 'KeyMaterial' --key-type ed25519 --key-format pem --output text > ${keyname}.pem
        chmod 0600 ${keyname}.pem
    else
        echo "Key $keyname already exists in your AWS account."  
        if [ ! -f ${keyname}.pem ]; then 
            echo Please copy ${keyname}.pem into this folder to ensure full functionality of pulumi. 
        fi
    fi
    if [ ! -f ${keyname}.pub ]; then 
        ssh-keygen -y -f ${keyname}.pem > ${keyname}.pub
    fi

up: 
    #!/bin/bash
    pulumi up -y
    just create-users 500 
