name: sjc-security
runtime:
  name: python
  options:
    toolchain: uv
config:
  rsw-ha:billing_code: load-testing
  rsw-ha:email: sam.cofer@posit.co
  rsw-ha:region: eu-west-1
  rsw-ha:my_ip: 73.58.130.128
