project:
  type: website

website:
  title: "Posit Workbench and AWS ParallelCluster"
  navbar:
    left:
      - href: Introduction.qmd
        text: Introduction 
      - href: AMI.qmd
        text: AMI
      - href: Pulumi.qmd
        text: Pulumi
      - href: Architecture.qmd
        text: Architecture
      - href: AWSParallelcluster.qmd 
        text: AWS ParallelCluster 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
