project:
  type: website

website:
  title: "today"
  navbar:
    left:
      - href: PWB.qmd
        text: Overview
      - href: AMI.qmd
        text: AMI
      - href: Architecture.qmd
        text: Architecture
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
